### ISSUE TITLE
Logout view change permission_classes

### ISSUE THREAD

**Issue by shaklev** [Tivix/django-rest-auth#332] opened 2017-05-18 09:43 UTC
Shouldn't the LogoutView have permission_classes set to `permission_classes = (IsAuthenticated,)` instead of `permission_classes = (AllowAny,)` , regardless of GET/POST method ?

* in addition in the `logout` function:

```
 def logout(self, request):
    try:
            request.user.auth_token.delete()
      except (AttributeError, ObjectDoesNotExist):
            pass
```
should be changed to 

```
   def logout(self, request):
        try:
            request.user.auth_token.delete()
        except (AttributeError, ObjectDoesNotExist):
            # handle NotAuthenticated
````

**Comment by Akay7** [comment] 2017-06-17 15:29
@shaklev 
How it can be useful? If you will make permission check on logout that will not make your app more faster.

**Comment by maxim-kht** [comment] 2017-06-22 15:12
Hi @shaklev, LogoutView does not return any sensitive data that is required to be guarded by a permission. If you wish to, you can extend this view and set the permission class in your app.

**Comment by shaklev** [comment] 2017-06-23 09:33
Hey @Akay7 @maxim-kht ,

I was looking from the perspective of "the correct response for every API call" but since the view doesn't return any sensitive data , a valid argument is that it doesn't have to be guarded.

**Comment by NikosVlagoidis** [comment] 2017-06-29 08:43
It is a bit confusing for the developer perspective as you test at first and it's not so clear as a response to say:
 "detail": "Successfully logged out." when actually nothing happened.
I think it is an easy fix.

**Comment by shaklev** [comment] 2017-06-29 08:45
^ that was my thought as well

**Comment by Akay7** [comment] 2017-06-29 09:34
@NikosVlagoidis if you prefer get 400 error on logout when user already anonymous, feel free to override logout view in your app and write a lot of custom logic on logout api inside client side app. 

But I though that not necessary in most applications. If you have any example of application where that necessary you can share with us.

**Comment by NikosVlagoidis** [comment] 2017-06-29 11:05
I am not saying it is necessary for the application and I don't say I cannot fix it.  I say it is a bit misleading to a person that tries to debug and test if the package is working correctly. And I think responses should represent somehow what happened and not only what it is necessary to work. It is just a suggestion.

**Comment by Akay7** [comment] 2017-06-29 11:14
@NikosVlagoidis I think more better follow the principle KISS

We can try to think about login response. For example I can imagine 4 cases:
1. User logged, but credentials is incorrect
2. User logged and credentials is correct
3. User not logged and credentials is incorrect
4. User not logged and credentials is correct
How you think more better give to user, more detail description about every of that case?

**Comment by NikosVlagoidis** [comment] 2017-06-29 11:33
I don't get how to keep it simple stupid has to do with keeping it misleading but anyway.

According to [http://django-rest-auth.readthedocs.io/en/latest/api_endpoints.html](url):

How can this happen exactly? Login returns a token if the credentials are correct and the validation happens server side. So if credentials are correct a Token returns to the client else you return Wrong credentials provided. It has nothing to do if you are logged in on the client. I don't see any logic about what you say or defined logged in and logged out better so i can get your point.

**Comment by Akay7** [comment] 2017-06-29 12:36
I'm just show few examples where response from server can depend from authenticated(or not) user. If you would like make different response to logout, then I guess make different response for login api(or make special permissions) will be your next step. And I mentioned if you don't know how it's can be useful, more better keep it simple as now.
Other case if you feel unhappy about incomplete description of logout api, you can update documentation and make PR.

**Comment by maxim-kht** [comment] 2018-04-16 00:07
Duplicate of https://github.com/Tivix/django-rest-auth/issues/174

**Closed by maxim-kht** 2018-04-16 00:07 UTC
