### ISSUE TITLE
Documenting responses to auth API endpoints

### ISSUE THREAD

**Issue by pramttl** [Tivix/django-rest-auth#216] opened 2016-06-03 21:42 UTC
Currently the [endpoint documentation](https://django-rest-auth.readthedocs.io/en/latest/api_endpoints.html), just contains the request types and the input parameters. There is no documentation on the response objects. It would be good to have that included too.

**Comment by pramttl** [comment] 2016-06-03 22:14
Djoser, which is a similar library also has response documentation: https://github.com/sunscrapers/djoser#endpoints

**Comment by Akay7** [comment] 2016-06-04 17:06
@pramttl Djoser returning not 403 error for unauth user?

**Comment by maxim-kht** [comment] 2016-12-08 01:13
Duplicate of https://github.com/Tivix/django-rest-auth/issues/280

**Closed by maxim-kht** 2016-12-08 01:13 UTC
