### ISSUE TITLE
Login with Google

### ISSUE THREAD

**Issue by umarmughal824** [Tivix/django-rest-auth#401] opened 2018-01-07 12:50 UTC
Whenever I give it 

access_key = id_token (obtained from android / ios app which had taken it from google api)

I get the following error.

Incorrect value.

**Comment by maxim-kht** [comment] 2018-01-20 01:06
Duplicate of https://github.com/Tivix/django-rest-auth/issues/262

**Closed** 2018-01-20 01:07 UTC
